name: turkic_flags
description: A comprehensive Flutter package providing high-resolution SVG flags, metadata, and customizable widgets for all Turkic world states and historical empires.
version: 1.0.5
homepage: https://github.com/Dijeo/turkic_flags
repository: https://github.com/Dijeo/turkic_flags
issue_tracker: https://github.com/Dijeo/turkic_flags/issues

topics:
  - flags
  - turkic
  - svg
  - widgets
  - ui

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ^3.9.2
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  vector_graphics: ^1.2.2
  vector_graphics_compiler: ^1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
